/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lab

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        
        assertNotNull(1, "app should have a greeting")
    }
}
